#!/bin/sh
# Linux Deploy Component
# (c) Anton Skshidlevsky <meefik@gmail.com>, GPLv3

NAME="openssh-server"
DESC="Secure shell (SSH) server"
DEPENDS=""
TARGET="debian:*:* ubuntu:*:* kalilinux:*:* archlinux:*:* fedora:*:* opensuse:*:* gentoo:*:* slackware:*:*"

[ -n "${SSH_PORT}" ] || SSH_PORT="22"

do_install()
{
    msg "Installing ${NAME} ... "
    local packages=""
    case "${DISTRIB}:${ARCH}:${SUITE}" in
    debian:*:*|ubuntu:*:*|kalilinux:*:*)
        packages="openssh-server"
        apt_install ${packages}
    ;;
    archlinux:*:*)
        packages="openssh"
        pacman_install ${packages}
    ;;
    fedora:*:*)
        packages="openssh-server"
        yum_install ${packages}
    ;;
    opensuse:*:*)
        packages="openssh"
        zypper_install ${packages}
    ;;
    gentoo:*:*)
        packages="openssh"
        emerge_install ${packages}
    ;;
    slackware:*:*)
        packages="openssh"
        slackpkg_install ${packages}
    ;;
    esac
}

do_configure()
{
    return 0
}

is_started()
{
    local is_started=""
    local f
    for f in /var/run/sshd.pid /run/sshd.pid
    do
        local pidfile="${CHROOT_DIR}${f}"
        local pid=$([ -e "${pidfile}" ] && cat "${pidfile}")
        if [ -n "${pid}" ]; then
            is_started=$(ps | awk '{if ($1 == '${pid}') print $1}')
            if [ -n "${is_started}" ]; then
                return 0
            fi
        fi
    done
    return 1
}

do_start()
{
    msg -n "${NAME} ... "
    is_started && { msg "skip"; return 0; }
    # prepare var
    [ -e "${CHROOT_DIR}/var/run" -a ! -e "${CHROOT_DIR}/var/run/sshd" ] && mkdir "${CHROOT_DIR}/var/run/sshd"
    [ -e "${CHROOT_DIR}/run" -a ! -e "${CHROOT_DIR}/run/sshd" ] && mkdir "${CHROOT_DIR}/run/sshd"
    # generate keys
    if [ -z "$(ls \"${CHROOT_DIR}/etc/ssh/\" | grep key)" ]; then
        chroot_exec su - root -c 'ssh-keygen -A'
        echo
    fi
    # exec sshd
    local sshd='`which sshd`'
    chroot_exec su - root -c "${sshd} -p ${SSH_PORT}"
    is_ok "fail" "done" || return 1
}

do_stop()
{
    msg -n "${NAME} ... "
    local pid=""
    local path
    for path in /run/sshd.pid /var/run/sshd.pid
    do
        if [ -e "${CHROOT_DIR}${path}" ]; then
            pid=$(cat "${CHROOT_DIR}${path}")
            break
        fi
    done
    if [ -n "${pid}" ]; then
        kill -9 ${pid}
        is_ok "fail" || return 1
    fi
    msg "done"
}

do_help()
{
cat <<EOF
   --ssh-port=PORT
     Port of SSH server.

EOF
}
