#!/bin/sh
# Linux Deploy Component
# (c) Anton Skshidlevsky <meefik@gmail.com>, GPLv3

NAME="sysv-init"
DESC="SysV init scripts support"
DEPENDS=""
TARGET="*:*:*"

do_install()
{
    return 0
}

do_configure()
{
    return 0
}

do_start()
{
    if [ -n "${INIT_LEVEL}" ]; then
        local item
        for item in $(ls "${CHROOT_DIR}/etc/rc${INIT_LEVEL}.d/" | grep '^S')
        do
            msg -n "${item/S[0-9][0-9]/} ... "
            chroot_exec su - root -c "/etc/rc${INIT_LEVEL}.d/${item} start"
            is_ok "fail" "done" || return 1
        done
    fi
}

do_stop()
{
    if [ -n "${INIT_LEVEL}" ]; then
        local item
        for item in $(ls "${CHROOT_DIR}/etc/rc6.d/" | grep '^K')
        do
            msg -n "${item/K[0-9][0-9]/} ... "
            chroot_exec su - root -c "/etc/rc${INIT_LEVEL}.d/${item} stop"
            is_ok "fail" "done" || return 1
        done
    fi
}

do_help()
{
cat <<EOF
   --init-level=NUM
     Number of init level, e.g 3.

EOF
}
