#!/bin/sh
# Linux Deploy Component
# (c) Anton Skshidlevsky <meefik@gmail.com>, GPLv3

NAME="vncserver"
DESC="Virtual network computing (VNC) server"
DEPENDS="desktop-base"
TARGET="debian:*:* ubuntu:*:* kalilinux:*:* archlinux:*:* fedora:*:* opensuse:*:* gentoo:*:*"

[ -n "${VNC_DISPLAY}" ] || VNC_DISPLAY="0"

do_install()
{
    msg "Installing ${NAME} ... "
    local packages=""
    case "${DISTRIB}:${ARCH}:${SUITE}" in
    debian:*:*|ubuntu:*:*|kalilinux:*:*)
        packages="tightvncserver"
        apt_install ${packages}
    ;;
    archlinux:*:*)
        packages="tigervnc"
        pacman_install ${packages}
    ;;
    fedora:*:*)
        packages="tigervnc-server"
        yum_install ${packages}
    ;;
    opensuse:*:*)
        packages="tightvnc"
        zypper_install ${packages}
    ;;
    gentoo:*:*)
        # set server USE flag for tightvnc
        if [ $(grep -c '^net-misc/tightvnc' "${CHROOT_DIR}/etc/portage/package.use") -eq 0 ]; then
            echo "net-misc/tightvnc server" >> "${CHROOT_DIR}/etc/portage/package.use"
        fi
        if [ $(grep -c '^net-misc/tightvnc.*server' "${CHROOT_DIR}/etc/portage/package.use") -eq 0 ]; then
            sed -i "s|^\(net-misc/tightvnc.*\)|\1 server|g" "${CHROOT_DIR}/etc/portage/package.use"
        fi
        packages="tightvnc"
        emerge_install ${packages}
    ;;
    esac
}

do_configure()
{
    msg "Configuring ${NAME} ... "
    local vnc_home="$(user_home)/.vnc"
    local vnc_home_chroot="${CHROOT_DIR}${vnc_home}"
    [ -e "${vnc_home_chroot}" ] || mkdir "${vnc_home_chroot}"
    # set vnc password
    [ -n "${USER_PASSWORD}" ] || USER_PASSWORD="changeme"
    echo ${USER_PASSWORD} | chroot_exec "vncpasswd -f" > "${vnc_home_chroot}/passwd" ||
    echo "MPTcXfgXGiY=" | base64 -d > "${vnc_home_chroot}/passwd"
    chmod 600 "${vnc_home_chroot}/passwd"
    rm "${vnc_home_chroot}/xstartup"
    ln -s ../.xinitrc "${vnc_home_chroot}/xstartup"
    chroot_exec chown -R ${USER_NAME}:${USER_NAME} "${vnc_home}"
}

is_started()
{
    local is_started=""
    local pidfile="${CHROOT_DIR}/tmp/xsession.pid"
    local pid=$([ -e "${pidfile}" ] && cat "${pidfile}")
    [ -n "${pid}" ] && is_started=$(ps | awk '{if ($1 == '${pid}') print $1}')
    [ -z "${is_started}" ] && return 1 || return 0
}

do_start()
{
    dbus_init()
    {
        [ -e "${CHROOT_DIR}/run/dbus/pid" ] && rm "${CHROOT_DIR}/run/dbus/pid"
        [ -e "${CHROOT_DIR}/var/run/messagebus.pid" ] && rm "${CHROOT_DIR}/var/run/messagebus.pid"
        chroot_exec dbus-daemon --system --fork &
    }
    msg -n "${NAME} ... "
    is_started && { msg "skip"; return 0; }
    dbus_init
    # remove locks
    [ -e "${CHROOT_DIR}/tmp/.X${VNC_DISPLAY}-lock" ] && rm "${CHROOT_DIR}/tmp/.X${VNC_DISPLAY}-lock"
    [ -e "${CHROOT_DIR}/tmp/.X11-unix/X${VNC_DISPLAY}" ] && rm "${CHROOT_DIR}/tmp/.X11-unix/X${VNC_DISPLAY}"
    # exec vncserver
    chroot_exec su - ${USER_NAME} -c "vncserver :${VNC_DISPLAY} ${VNC_ARGS}"
    is_ok "fail" "done" || return 1
}

do_stop()
{
    msg -n "${NAME} ... "
    local pid=""
    if [ -e "${CHROOT_DIR}/tmp/xsession.pid" ]; then
        pid=$(cat "${CHROOT_DIR}/tmp/xsession.pid")
    fi
    if [ -n "${pid}" ]; then
        kill -9 ${pid} || { msg "fail"; return 1; }
    fi
    msg "done"
}

do_help()
{
cat <<EOF
   --vnc-display=DISPLAY 
     Display of VNC server, e.g 0.

   --vnc-args=STR
     Defines other vncserver options, separated by a space.

EOF
}
