#!/bin/sh
# Linux Deploy Component
# (c) Anton Skshidlevsky <meefik@gmail.com>, GPLv3

NAME="xserver"
DESC="Start up GUI on external X server"
DEPENDS="desktop-base"
TARGET="*:*:*"

[ -n "${XSERVER_DISPLAY}" ] || XSERVER_DISPLAY="0"

do_install()
{
    return 0
}

do_configure()
{
    return 0
}

is_started()
{
    local is_started=""
    local pidfile="${CHROOT_DIR}/tmp/xsession.pid"
    local pid=$([ -e "${pidfile}" ] && cat "${pidfile}")
    [ -n "${pid}" ] && is_started=$(ps | awk '{if ($1 == '${pid}') print $1}')
    [ -z "${is_started}" ] && return 1 || return 0
}

do_start()
{
    dbus_init()
    {
        [ -e "${CHROOT_DIR}/run/dbus/pid" ] && rm "${CHROOT_DIR}/run/dbus/pid"
        [ -e "${CHROOT_DIR}/var/run/messagebus.pid" ] && rm "${CHROOT_DIR}/var/run/messagebus.pid"
        chroot_exec dbus-daemon --system --fork
    }
    msg -n "${NAME} ... "
    dbus_init
    chroot_exec su - ${USER_NAME} -c "export DISPLAY=${XSERVER_HOST}:${XSERVER_DISPLAY}; ~/.xinitrc &"
    is_ok "fail" "done" || return 1
}

do_stop()
{
    msg -n "${NAME} ... "
    local pid=""
    if [ -e "${CHROOT_DIR}/tmp/xsession.pid" ]; then
        pid=$(cat "${CHROOT_DIR}/tmp/xsession.pid")
    fi
    if [ -n "${pid}" ]; then
        kill -9 ${pid} || { msg "fail"; return 1; }
    fi
    msg "done"
}

do_help()
{
cat <<EOF
   --xserver-display=DISPLAY 
     Display of X server, e.g 0.

   --xserver-host=HOST
     Hostname or IP of X server.

EOF
}
